// using Barrel Pattern

export {default as About} from './about'
export {default as AddToCartBtn} from './addToCartBtn'
export {default as ArrowUp} from './arrow-up'
// export {default as Authentication} from './auth'
export {default as Breakfast} from './breakfast'
export {default as Dinner} from './dinner'
export {default as Footer} from './footer'
export {default as Faq} from './faq'
export * from './faqList'
export {default as Guides} from './how_it_works'
export {default as HomePage} from './homepage' 
export {default as HomePageBookTable} from './homepage_book_table'
export {default as Header} from './header'
export {default as LandingPage} from './coming_soon'
export {default as Lunch} from './lunch'
export {default as Order} from './order'
export {default as Reservation} from './reservation'
export {default as SingleFaq} from './singleFaq'
export {default as ViewCart} from './view-cart-page'
export * from './arrayOfObjects';
export * from './locations'
